name: Open API

env:
  java: 11

on:
  push:
    branches: [ openapi-canary ]

jobs:
  test:
    name: build/commit openAPI spec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          git status
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push