name: OpenAPI Canary

on:
  schedule:
    - cron: '0 13 * * *'

jobs:
  canary:
    name: Check for changed spec file
    runs-on: ubuntu-latest

    steps:
      - name: Check out development branch
        uses: actions/checkout@v2
        with:
          ref: development
          path: head

      - name: Check out master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: base
      - name: Run OpenAPI Diff for external journal API
        uses: mvegter/openapi-diff-action@v0.23.3
        with:
          head-spec: head/openapi/external_journal_API.yaml
          base-spec: base/openapi/external_journal_API.yaml